# Backend ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
  labels:
    app: todo-backend
data:
  MONGO_HOST: "mongodb-svc" 
  USE_DB_AUTH: "true"
  PORT: "8080"  
