# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: dev
  labels:
    app: todo-frontend
spec:
  type: ClusterIP
  selector:
    app: todo-frontend
  ports:
  - port: 80
    targetPort: frontend-port
    protocol: TCP
